title: "Douglas Mbura"
description: "Engineer | Data Coordinator | Indigenous AI Advocate"
theme: jekyll-theme-slate
show_downloads: false

# Enable plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
